In [14]:
year = int(input("Enter the value of a year:"))
if(year%4==0):
    if(year%100==0):
        if(year%400==0):
            print(year,"is a Leap Year")
        else:
            print("{0} is not a Leap Year".format(year))
    else:
        print("{0} is not a Leap Year".format(year))
else:
    print(year,"is not a Leap Year")

Enter the value of a year:5200
5200 is a Leap Year


In [17]:
#Maximum of three numbers
num1 = int(input("Enter the first number"))
num2 = int(input("Enter the second number"))
num3 = int(input("Enter the third number"))
if(num1>num2):
    if(num1>num3):
        print("{0} is greatest".format(num1))
    else:
        print("{0} is greatest".format(num3))
elif(num2>num3):
    print("{0} is greatest".format(num2))
else:
    print("{0} is greatest".format(num3))

Enter the first number25
Enter the second number36
Enter the third number35
36 is greatest


In [29]:
#Python program to check the given number is prime number or not.
prime = int(input("Enter the Number to be checked : "))
for i in range(2, prime):
    if (prime%i) == 0:
        print("{0} is not a prime number".format(prime))
        print(i,"multiplied by",prime//i,"is",prime)
        break
else:
    print("{0} is a prime number".format(prime))

Enter the Number to be checked : 25
25 is not a prime number
5 multiplied by 5 is 25


In [14]:
#Write a Python program to print first n Fibonacci numbers
def fibonac(f):
    if f<=1:
        return f
    else:
        return fibonac(f-1)+fibonac(f-2)
fibo = int(input("Enter the number : "))
for i in range(fibo):
    print(fibonac(i)," ",i)

Enter the number : 26
0   0
1   1
1   2
2   3
3   4
5   5
8   6
13   7
21   8
34   9
55   10
89   11
144   12
233   13
377   14
610   15
987   16
1597   17
2584   18
4181   19
6765   20
10946   21
17711   22
28657   23
46368   24
75025   25


In [5]:
observe1="What's happening!!"
def passport_check(passport_no):
    observe4="actual copied to formal"
    observe5="func. execution starts"
    if(len(passport_no)==8):
        if(passport_no[0]>="A" and passport_no[0]<="Z"):
            status="valid"
        else:
            status="invalid"
    else:
        status= "invalid"
    observe6="func. execution ends"
    return status
observe2="function with formal arg."
observe3="calling with actual arg."
passport_status=passport_check("M9993471")
print("Passport is",passport_status)
#observe1,2,3,4,5,6 are temporary variables used to explain this concept

Passport is valid


In [6]:
wt_limit=30
def baggage_check(baggage_wt):
    extra_baggage_charge=0
    if not(baggage_wt>=0 and baggage_wt<=wt_limit):
        extra_baggage=baggage_wt-wt_limit
        extra_baggage_charge=extra_baggage*100
    return extra_baggage_charge
def update_baggage_limit(new_wt_limit):
    wt_limit=new_wt_limit
    print("This airline now allows baggage limit till",wt_limit,"kgs")
print("This airline allows baggage limit till",wt_limit,"kgs")
print("Pay the extra baggage charge of",baggage_check(35),"rupees")
update_baggage_limit(45)
print("Pay the extra baggage charge of",baggage_check(35),"rupees")


This airline allows baggage limit till 30 kgs
Pay the extra baggage charge of 500 rupees
This airline now allows baggage limit till 45 kgs
Pay the extra baggage charge of 500 rupees


In [15]:
result=0

def find_sum(num1,num2):
    if(num1!=num2):
        result=num1+num2
    else:
        result=2*(num1+num2)

        find_sum(3,4)
print(result)
find_sum(5,5)
print(result)

0
0


In [18]:
my_list=[0]*5
for index in range(1,5):
	my_list[index]=(index-1)*10
print(my_list)

[0, 0, 10, 20, 30]


In [24]:
tuple1=(5,10,15,20,25)
print(tuple1[5])

IndexError: tuple index out of range

In [28]:
sample_dict={'a':1,'b':2}
sample_dict.update({'b':5, 'c':10 })
print(sample_dict.get('a'),sample_dict.get('b'),sample_dict.get('c'))

1 5 10


In [1]:
import numpy as np
arr1 = [25, 56, 12, 85, 34, 75]
arr2 = [42, 3, 86, 32, 856, 46]

In [44]:
Narr = np.random.rand(1,6)

In [46]:
Narr = Narr.astype('complex128')

In [47]:
Narr

array([[0.60267748+0.j, 0.50163871+0.j, 0.46355035+0.j, 0.8594488 +0.j,
        0.2713341 +0.j, 0.09711171+0.j]])

In [11]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.diag([4,5,6],2)

array([[0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
lst = [5,10,0,200]
lst1 = [1,2,3,'text',True,3+2j]
import numpy as np
arr = np.array(lst)

In [16]:
print(arr+5)

[ 10  15   5 205]


In [17]:
arr1 = np.array(lst1)

In [19]:
arr1

array(['1', '2', '3', 'text', 'True', '(3+2j)'], dtype='<U11')

In [21]:
print(arr.nbytes)

16


In [22]:
arr1 = np.zeros(10)

In [23]:
print(np.result_type(arr1))

float64


In [28]:
arr3 = np.arange(4).reshape(4,-1)

In [29]:
print(arr3.shape)

(4, 1)


In [30]:
print(arr3.shape)

(4, 1)


In [1]:
a = "Welcome to Infosys"
print(a[:2])

We


In [16]:
result=0

def find_sum(num1,num2):
    if(num1!=num2):
        result=num1+num2
        return result
    else:
        result=2*(num1+num2)
        return result
    
print(find_sum(3,4))
print(result)
print(find_sum(5,5))
print(result)

7
0
20
0


## LIST OPERATIONS

In [36]:
#Creating an empty list
sample_list=[]

In [37]:
sample_list

[]

In [19]:
#Creating a list with known size and known elements
sample_list1 = ["Mark",5,"Chan",9]

In [20]:
sample_list1

['Mark', 5, 'Chan', 9]

In [23]:
#Creating a list with known size and unknown elements
#None denotes an unknown value in Python
sample_list2 = [None]*5

In [24]:
sample_list2

[None, None, None, None, None]

In [25]:
#Length of the list
len(sample_list1)

4

In [27]:
#Random read
print(sample_list1[2])

Chan


In [28]:
#Random write
sample_list2[2]="James"

In [29]:
sample_list2

[None, None, 'James', None, None]

In [33]:
#Concatenating two lists
new_list=["Henry","Quentin"]
sample_list2 = sample_list2+new_list
#sample_list2=sample_list2+new_list, creates a new list named sample_list2 
#containing the concatenated elements from the original sample_list2 and new_list

In [34]:
new_list

['Henry', 'Quentin']

In [35]:
sample_list2

[None, None, 'James', None, None, 'Henry', 'Quentin']

In [38]:
sample_list

[]

In [39]:
sample_list+=new_list

In [40]:
sample_list

['Henry', 'Quentin']

In [41]:
sample_list+=new_list

In [42]:
sample_list

['Henry', 'Quentin', 'Henry', 'Quentin']

In [43]:
sample_list=sample_list+new_list

In [44]:
sample_list

['Henry', 'Quentin', 'Henry', 'Quentin', 'Henry', 'Quentin']

In [45]:
sample_list2+=new_list

In [46]:
sample_list2

[None, None, 'James', None, None, 'Henry', 'Quentin', 'Henry', 'Quentin']

In [47]:
list_of_airlines=["AL1","AL2","AL3"]

In [48]:
for i in range(0,len(list_of_airlines)):
    print(list_of_airlines[i])

AL1
AL2
AL3


In [51]:
#This is beautiful
for airline in list_of_airlines:
    print(airline)

AL1
AL2
AL3


In [50]:
#If we just want to find out whether an element is there in a list, we need not iterate through the list. 
#Instead we can check using if..in syntax. Try out the code and observe the results.
list_of_airlines=["AL1","AL2","AL3"]
airline="AL3"
if airline in list_of_airlines:
    print("Airline found")
else:
    print("Airline not found")

Airline found


In [52]:
#To fetch the second last airline in the list, 
#we can write list_of_airlines[-2]. This is equivalent to list_of_airlines[len(list_of_airlines)-2]. 
list_of_airlines[-2]

'AL2'

In [69]:
def checkNum(list_num,pos):
    for i in range(0,len(list_num)):
        print(i)
        if pos==list_num[i]:
            return list_num[i]
        else:
            return 0

In [70]:
checkNum([1,2,2,3,4,4,4,10],3)

0


0

In [120]:
def adjacentNum(list_num):
    count=0
    for i in range(0,len(list_num)):
        if i==list_num[i]:
            count+=1
            print("{} has occured at position {}".format(list_num[i],i))
    return count

In [122]:
adjacentNum([8, 6, 8, 10, 8, 20, 10, 8, 8])

8 has occured at position 8


1

## TUPLE OPERATIONS

In [124]:
#TUPLES ARE IMMUTABLE
#Elements can be homogeneous or heterogeneous but they are READ-ONLY.

In [125]:
#CREATING A TUPLE
lunch_menu=("Welcome Drink","Veg Starter","Non-Veg Starter","Veg Main Course","Non-Veg Main Course","Dessert")

In [126]:
#READ FROM A TUPLE LIST
lunch_menu[0]

'Welcome Drink'

In [127]:
#WRITE INTO A TUPLE LIST IS NOT ALLOWED
lunch_menu[0]="Shangrila"

TypeError: 'tuple' object does not support item assignment

In [129]:
#APPEND INTO A TUPLE IS NOT ALLOWED
lunch_menu.append("Glasss")

AttributeError: 'tuple' object has no attribute 'append'

## STRING OPERATION

In [130]:
#STRING IS IMMUTABLE

In [131]:
s = "ABCD"

In [132]:
s[0]

'A'

In [133]:
s[0]="Z"

TypeError: 'str' object does not support item assignment

In [139]:
#Creating a string
pancard_number="AABGT6715H"
#Length of the string
print("Length of the PAN card number:", len(pancard_number))
#Concatenating two strings
name1 ="PAN "
name2="card"
name=name1+name2
print(name)
#print("Iterating the string using range()")
#for i in range(0,len(pancard_number)):
#    print("{0} is the values in place indexed at {1}".format(pancard_number[i],i))
#print("Iterating the string using keyword in")
#for v in pancard_number:
#    print(v)
# print("Searching for a character in string")
# if "Z" in pancard_number:
#     print("Character present")
# else:
#     print("Character is not present")
# #Slicing a string
# print("The numbers in the PAN card number:", pancard_number[5:9])
# print("Last but one 3 characters in the PAN card:",pancard_number[-4:-1])
# pancard_number[2]="A" #This line will result in an error, i.e., string is immutable
# print(pancard_number)

Length of the PAN card number: 10
PAN card
Iterating the string using keyword in
A
A
B
G
T
6
7
1
5
H


In [148]:
#Ticket for Airline
def tickerGen(airline,src,dest):
    if src!=dest:
        printTic = airline+':'+src+':'+dest
    else:
        printTic = "Source and Destination cannot be same"
    return printTic

In [150]:
print(tickerGen("AL1","BBI","BBI"))

Source and Destination cannot be same


## SET OPERATION

In [151]:
#Set can be created by using the keyword set or by using curly braces {}. 
#Set function is used to eliminate duplicate values in a list.
#Creating a set
flight_set={500,520,600,345,520,634,600,500,200,200}

In [152]:
flight_set

{200, 345, 500, 520, 600, 634}

In [153]:
#Eliminating duplicates from a list
passengers_list=["George", "Annie", "Jack", "Annie", "Henry", "Helen", "Maria", "George", "Jack", "Remo"]
unique_passengers=set(passengers_list)

In [154]:
unique_passengers

{'Annie', 'George', 'Helen', 'Henry', 'Jack', 'Maria', 'Remo'}

In [155]:
#Common elements between two sets
flight_set&unique_passengers

set()

In [156]:
#Elements that are only in set A
flight_set-unique_passengers

{200, 345, 500, 520, 600, 634}

In [157]:
#Merges elements of set A and set B
flight_set|unique_passengers

{200,
 345,
 500,
 520,
 600,
 634,
 'Annie',
 'George',
 'Helen',
 'Henry',
 'Jack',
 'Maria',
 'Remo'}

## DICTIONARY OPERATION

In [160]:
#A dictionary can be used to store an unordered collection of key-value pairs. 
#The key should be unique and can be of any data type. 
#Like lists, dictionaries are mutable.
#Creating a dictionary
crew_details={ "Pilot":"Kumar","Co-pilot":"Raghav","Head-Strewardess":"Malini","Stewardess":"Mala" }

In [161]:
#Accessing the value using key
crew_details["Pilot"]

'Kumar'

In [162]:
#Iterating through the dictionary
for key,value in crew_details.items():
     print(key,":",value)

Pilot : Kumar
Co-pilot : Raghav
Head-Strewardess : Malini
Stewardess : Mala
